Yonetim.UI.Web/Controllers/HaberController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yonetim.BLL.Repository;
using Yonetim.Model.Entities;
using Yonetim.Model.ViewModels;
using Yonetim.UI.Web.Models;


namespace Yonetim.UI.Web.Controllers
{
    public class HaberController : Controller
    {
        // GET: Haber
        public ActionResult Index()
        {
            var model = new HaberRepo().GetAll().Select(x => new HaberViewModel()
            {
                Id = x.Id,
                Kategoriler = x.Kategoriler.Select(y => y.Id).ToList(),
                Baslik=x.Baslik,
                Keywords=x.Keywords,
                Icerik=x.Icerik,
                YayindaMi=x.YayindaMi,
                EklenmeZamani=x.EklenmeZamani,
                Hit=x.Hit
            }).ToList();
            return View(model);
        }
        public ActionResult Ekle()
        {
            //var kategoriler = new KategoriRepo().GetAll().OrderBy(x => x.Ad).ToList();
            //var kategoriSelectList = new List<SelectListItem>();
            //foreach(var item in kategoriler)
            //{
            //    kategoriSelectList.Add(new SelectListItem
            //    {
            //        Value = item.Id.ToString(),
            //        Text=item.Ad

            //    });

            //} // burayı komple dropdownlistdoldurucu ya kopyaladık. Çünkü bu methodu başka yerlerde de kullanacağımız için class yaptık onu model in içine. 
            ViewBag.Kategoriler = DropDownListDoldurucu.KategoriList();    // bir hata durumunda comboların dolu gelmesi için bu methodu yazdık.
            return View();
        }
        [HttpPost][ValidateInput(false)] //bu validateinput u internet sayfasına html gönderdiğimizde asp bunu default olarak atıp bize hata vermesin diye attık. Summernote ile yaptığımız değişikliklerle de resim vs de ekleyebiliyoruz artık ama bunu başa koymak lazım. 
        public ActionResult Ekle(HaberViewModel model)
        {
            ViewBag.Kategoriler = DropDownListDoldurucu.KategoriList();
            if (!ModelState.IsValid)
            {

                ModelState.AddModelError("", "Haber eklerken bir hata meydana geldi");
                return View(model);
            }
            try
            {
                // var kategoriler = new KategoriRepo().GetAll().Where(x => model.Kategoriler.Contains(x.Id)).ToList();
                //bunu zaten gittik artık repository de yaptık.
                new HaberRepo().Insert(model);
                return RedirectToAction("Index");
            }
            catch 
            {
                return View(model);
            }
            
        }
        public ActionResult Duzenle(int? id)
        {
            if (id==null)
            return RedirectToAction("Index");
            var haber = new HaberRepo().GetByID(id.Value);
            if (haber==null)
                return RedirectToAction("Index");
            var kategoriList = DropDownListDoldurucu.KategoriList();
            //ViewData["Kategoriler"]; Bu üsttekinin aynısıdır aslında. 
            
            foreach (var item in kategoriList)
            {
                if (haber.Kategoriler.Select(x=>x.Id).Contains(int.Parse(item.Value)))
                {
                    item.Selected= true;
                }
            }
            ViewBag.Kategoriler = kategoriList.OrderByDescending(x => x.Selected);

            var model = new HaberViewModel() 
            {
                Icerik = haber.Icerik,
                Id = haber.Id,
                Kategoriler = haber.Kategoriler.Select(x => x.Id).ToList(),
                Baslik = haber.Baslik,
                Keywords = haber.Keywords,
                YayindaMi = haber.YayindaMi,
                EklenmeZamani = haber.EklenmeZamani

            };
            return View(model);
            
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Duzenle(HaberViewModel model)
        {
            ViewBag.Kategoriler = DropDownListDoldurucu.KategoriList();
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Haber düzenlenirken bir hata oluştu");
                return View(model);
            }
            try
            {
                new HaberRepo().Update(model);
                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException e)
            {
                ModelState.AddModelError("", e.Message);
                return View(model);
            }

        }
    }
}

Yonetim.UI.Web/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yonetim.BLL.Repository;
using Yonetim.Model.Entities;
using Yonetim.Model.ViewModels;

namespace Yonetim.UI.Web.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori
        public ActionResult Index()
        {
            var model = new KategoriRepo().GetAll().Select(x => new KategoriViewModel()
            {
                Id = x.Id,
                Ad = x.Ad,
                Aciklama = x.Aciklama

            }).ToList();
            return View(model);
        }
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost] // iki tane ekle methodu olduğu için çakışma yapmasın diye bunuyazıyoruz. 
        public ActionResult Ekle(KategoriViewModel model)
        {
            try
            {
                new KategoriRepo().Insert(new Kategori()
                {
                    Ad = model.Ad,
                    Aciklama = model.Aciklama

                });
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
            
        }

        public ActionResult Duzenle(int? id)
        {
            if (id==null)
                return RedirectToAction("Index");
            var kategori = new KategoriRepo().GetByID(id.Value);
            if (kategori==null)
          
                return RedirectToAction("Index");

            var model = new KategoriViewModel()
            {
                Id = kategori.Id,
                Ad = kategori.Ad,
                Aciklama = kategori.Aciklama

            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Duzenle(KategoriViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Kategori güncelleme işleminde hata oluştu");
                return View(model);
            }
            try
            {
                var kategori = new KategoriRepo().GetByID(model.Id);
                kategori.Ad = model.Ad;
                kategori.Aciklama = model.Aciklama;
                new KategoriRepo().Update();
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                return View(model);
             
            }
        }
    }
}

Yonetim.UI.Web/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yonetim.BLL.Repository;
using Yonetim.Model.ViewModels;

namespace Yonetim.UI.Web.Controllers
{
    public class SiteController : Controller
    {
        // GET: Site
        public ActionResult Index()
        {
            var model = new HaberRepo().GetAll().Where(x => x.YayindaMi).Select(x => new HaberViewModel()
            {
                Id=x.Id,
                Baslik=x.Baslik,
                EklenmeZamani=x.EklenmeZamani,
                Hit=x.Hit,
                Icerik=x.Icerik,
                Keywords=x.Keywords

            }).ToList();
            return View(model);
        }
        public ActionResult Haber(int? id)
        {
            if (id == null) return RedirectToAction("Index");
            var haber = new HaberRepo().GetByID(id.Value);
            if (haber == null)
            {
                return RedirectToAction("Index");
            }
            //şimdi buraya hit içinde bir method dönmeliyiz. Aslında bu işi siteler ip adresi ile bakıyor. Ama bir sayfanın açılış kapanışıyla yapacağız
            haber.Hit++;
            new HaberRepo().Update();
            return View(haber);
        }
        
    }
}

Yonetim.UI.Web/Views/Shared/_NavHeaderPartialPage.cshtml
@*Bu da başlık için partiallayout. Bunların alayını adminlayout a ekleyip bırakacağız her click eventimizde. Ama admin layout değişmeyecek, partial ler değişecek.*@ 
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html">Taş Haber Sitesi</a>
</div>

Yonetim.UI.Web/Views/Shared/_NavRightPartialPage.cshtml
@*Sağdaki kutucukları için olan divler. blank.html den*@ 
<ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-messages">
            <li>
                <a href="#">
                    <div>
                        <strong>John Smith</strong>
                        <span class="pull-right text-muted">
                            <em>Yesterday</em>
                        </span>
                    </div>
                    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <strong>John Smith</strong>
                        <span class="pull-right text-muted">
                            <em>Yesterday</em>
                        </span>
                    </div>
                    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <strong>John Smith</strong>
                        <span class="pull-right text-muted">
                            <em>Yesterday</em>
                        </span>
                    </div>
                    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a class="text-center" href="#">
                    <strong>Read All Messages</strong>
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        </ul>
        <!-- /.dropdown-messages -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-tasks">
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 1</strong>
                            <span class="pull-right text-muted">40% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                <span class="sr-only">40% Complete (success)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 2</strong>
                            <span class="pull-right text-muted">20% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                <span class="sr-only">20% Complete</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 3</strong>
                            <span class="pull-right text-muted">60% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                <span class="sr-only">60% Complete (warning)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 4</strong>
                            <span class="pull-right text-muted">80% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                <span class="sr-only">80% Complete (danger)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a class="text-center" href="#">
                    <strong>See All Tasks</strong>
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        </ul>
        <!-- /.dropdown-tasks -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-alerts">
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-comment fa-fw"></i> New Comment
                        <span class="pull-right text-muted small">4 minutes ago</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                        <span class="pull-right text-muted small">12 minutes ago</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-envelope fa-fw"></i> Message Sent
                        <span class="pull-right text-muted small">4 minutes ago</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-tasks fa-fw"></i> New Task
                        <span class="pull-right text-muted small">4 minutes ago</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-upload fa-fw"></i> Server Rebooted
                        <span class="pull-right text-muted small">4 minutes ago</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a class="text-center" href="#">
                    <strong>See All Alerts</strong>
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        </ul>
        <!-- /.dropdown-alerts -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>

Yonetim.UI.Web/Views/Shared/_SideBarPartialPage.cshtml
@*Soldaki arama için olan divler gelecek*@ 
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Ara...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </li>
            @*<li>
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>*@
            <li>
                <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Haberler <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Index","Haber")">Haberler</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Ekle","Haber")">Yeni Haber Ekle</a> @*//haber ekleme linkini aktif yaptık.*@ 
                    </li>
                    
                </ul>
                <!-- /.nav-second-level -->
            </li>
            <li>
                <a href="tables.html"><i class="fa fa-table fa-fw"></i> Kategoriler <span class="fa arrow"></span> </a> @*bu spanı yukarıdan eklersen bizim de okumuz olur*@
                <ul class="nav nav-second-level">
                    <li>
                        <a href="@Url.Action("Duzenle","Kategori")">Kategori Düzenle</a> 
                    </li>
                    <li>
                        <a href="@Url.Action("Ekle","Kategori")">Yeni Kategori Ekle</a>
                    </li>
                    
                </ul>
            </li>

            <li>
                <a href="@Url.Action("Index","Site")"><i class="fa fa-table fa-fw"></i> Haberleri Görüntüle  </a> @*bu spanı yukarıdan eklersen Buton üstünde ok  olur. Eğer açılır bir pencere istiyorsan span atarsın, bunda ise gerek yok. *@
               
            </li>
            @*<li>
                <a href="forms.html"><i class="fa fa-edit fa-fw"></i> Form </a>
            </li>*@
            @*<li>*@
                @*<a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="panels-wells.html">Panels and Wells</a>
                    </li>
                    <li>
                        <a href="buttons.html">Buttons</a>
                    </li>
                    <li>
                        <a href="notifications.html">Notifications</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                    <li>
                        <a href="icons.html"> Icons</a>
                    </li>
                    <li>
                        <a href="grid.html">Grid</a>
                    </li>
                </ul>*@
                <!-- /.nav-second-level -->
            @*</li>*@
            @*<li>
                <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Third Level <span class="fa arrow"></span></a>
                        <ul class="nav nav-third-level">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                        </ul>
                        <!-- /.nav-third-level -->
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>*@
            <li class="active">
                @*<a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>*@
                <ul class="nav nav-second-level">
                    @*<li>
                        <a class="active" href="blank.html">Blank Page</a>
                    </li>*@
                    @*<li>
                        <a href="login.html">Login Page</a>
                    </li>*@
                </ul>
                <!-- /.nav-second-level -->
            </li>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>